baseURL = 'https://bromo.art.br/'
title = 'Bromo Blog'
theme = 'BromaticTheme'

defaultContentLanguage = "pt-BR" 

[languages]
  [languages.pt-BR]
    label = "Português (Brasil)"
    locale = "pt-BR"
    timeZone = "America/Bahia"

[markup.goldmark.renderHooks.image]
useEmbedded = 'fallback'

[markup.goldmark.renderHooks.link]
useEmbedded = 'fallback'

[taxonomies]
  tag = "tags"

[pagination]
  pagerSize = 8